---
project_name: stctl

release:
  github:
    owner: stacksciences 
    name: stctl

builds:
  - main : ./
    binary: stctl
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags: -X main.Version={{.Version}} -X main.GitTag={{.Tag}} -X main.BuildDate={{.Date}}
    env:
      - CGO_ENABLED=0
    archive:
      replacements:
        linux: Linux
        darwin: Osx
        windows: Windows
        amd64: x86_64